import "reflect-metadata";
import "@angular/platform-browser";
import "@angular/core";
import "@angular/common";
import "@angular/forms";
import "@angular/router";
import "ngx-cookie-service"
import "@ngx-translate/core"
import "@ngx-translate/http-loader"